### ISSUE TITLE
Send data collected from camera through wifi issue

### ISSUE THREAD

**Issue by jixunx** [igrr/esp32-cam-demo#26] opened 2017-03-09 03:54 UTC

**Comment by jixunx** [comment] 2017-03-30 08:35
Amoth ago.I disable PWM of esp32,and make the clock of camera from external crystal.The issue has fixed.Maybe PWM infect the wifi function.

**Comment by krzychb** [comment] 2017-03-30 12:25
Looks like a duplicate of #27

**Closed by krzychb** 2017-03-30 12:25 UTC
